version: "3.9"

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-rinha
    command: >
      redis-server
      --maxmemory 64mb
      --maxmemory-policy volatile-ttl
      --save ""
      --appendonly no
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - rinha-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 70M

  api01: &api
    # image: guilhermecfmello/rinha-backend-2025
    build:
      context: ./api
      dockerfile: Dockerfile
    hostname: api01
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - payment-processor
      - rinha-net
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.32"
          memory: "70MB"

networks:
  payment-processor:
    external: true
  rinha-net:
    driver: bridge