import os

class Config:
    LOG_LEVEL = os.getenv("LOG_LEVEL")
    REDIS_URL = os.getenv("REDIS_URL")
    RINHA_TOKEN = os.getenv("RINHA_TOKEN")
    PAYMENT_REQUEST_QUEUE = os.getenv("PAYMENT_REQUEST_QUEUE")
    PAYMENT_SUCCESS_TABLENAME = os.getenv("PAYMENT_SUCCESS_TABLENAME")
    PROCESSOR_DEFAULT_URL = os.getenv("PROCESSOR_DEFAULT_URL")
    PROCESSOR_FALLBACK_URL = os.getenv("PROCESSOR_FALLBACK_URL")